#!/usr/bin/env bash
set -e # exit immediately if a command has nonzero exit code
pushd ~/nixos

# Early return if no changes were detected (thanks @singiamtel!)
if git diff --quiet; then
    echo "No changes detected, exiting."
    popd
    exit 0
fi

git diff -U0

read -p "OK to push and rebuild? (y/n) " -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]] then
	exit 1
fi
echo

echo "NixOS is rebuilding..."
sudo nixos-rebuild switch --flake ./#default &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
current=$(sudo nix-env -p /nix/var/nix/profiles/system --list-generations | grep "current")
git commit -am "gen $(current::-9)"
popd
echo "NixOS rebuilt successfully! (gen $current)"
